### PR TITLE
PrtSc key recognition

### PR DESCRIPTION
**Pull request by bakatrouble**
First digit in keycode was stripped (length of "key_code=" is 9, not 10), so fixed (lines 34, 50)
Maybe some additional edits required

### CODE REVIEW

**Comment by emmatyping** [comment]
I'll go over this. Thanks for catching that!

**Comment by emmatyping** [comment]
@bakatrouble Looks good, thank you for contributing. I am wondering what your opinion is on `key=self.keylist[95]`. Wouldn't it be faster just to say `key="PrtSc"`?

**Comment by bakatrouble** [comment]
Just did it the same way it was made for other keys, for code style consistency

Just curious, what are those empty key names for?

**Comment by emmatyping** [comment]
Makes sense. 

The empty keys are for non-standard keyboards (I think). There are many layouts, and not all numbers are applicable. The original "Null" is not used b/c numbering starts at 1 not 0.

**Pull request merged**
